export type OfficeSupplyItem = {
  key: string
  name: string
  price: number
  max: number
  min: number
  description?: string
  imageUrl?: string
  productUrl?: string
}

export type OfficeSupplySection = {
  key: string
  title: string
  items: OfficeSupplyItem[]
}

/**
 * Office Supplies order catalog.
 * `min` is the "on hand" minimum the warehouse keeps; the orderable quantity is
 * 0..`max`. Prices and limits mirror the official FIS order form.
 */
export const OFFICE_SUPPLY_SECTIONS: OfficeSupplySection[] = [
  {
    key: 'office',
    title: 'Office Supplies',
    items: [
      {
        key: 'shipping-labels',
        name: 'Shipping Labels',
        price: 34.98,
        min: 1,
        max: 2,
        description: 'Avery Printable Shipping Labels with Sure Feed, 3-1/3" x 4", White, 600 Blank Mailing Labels (5164)',
        imageUrl: 'https://m.media-amazon.com/images/I/81-6bogxksL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B00006HX4B',
      },
      {
        key: 'printer-paper',
        name: 'Printer/Copy Paper',
        price: 77.99,
        min: 1,
        max: 2,
        description: '20 Lb. Copy Paper, 8.5 x 11 - 8 Ream (4,000 Sheets), 92 Bright, Made in the USA',
        imageUrl: 'https://m.media-amazon.com/images/I/71M2jqoK7XL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B072FVQNWM',
      },
      {
        key: 'postit-pads',
        name: 'Lined Post-it Note Pads',
        price: 21.99,
        min: 1,
        max: 2,
        description: 'Lined Sticky Notes 3 x 3, 20 Pack Box, 2,000 Sheets (100/Pad), Bright Assorted Colors',
        imageUrl: 'https://m.media-amazon.com/images/I/81WwFnxXKlL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B095B7RBQN',
      },
      {
        key: 'staples',
        name: 'Bostitch Office Premium Standard Staples (1 box)',
        price: 5.5,
        min: 1,
        max: 4,
        description: 'Full strip staples - each strip contains 210 staples, 1/4" leg length, 5,000 staples per box',
        imageUrl: 'https://m.media-amazon.com/images/I/81UBYFDWtpL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B00J8PJJF0',
      },
      {
        key: 'pen-blue',
        name: 'Ink Pen - Blue',
        price: 4.99,
        min: 1,
        max: 2,
        description: 'BIC Round Stic Xtra Life Blue Ballpoint Pens, Medium Point (1.0mm), 60-Count Pack',
        imageUrl: 'https://m.media-amazon.com/images/I/71ZuQnEGl1L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B001Q4HUNO',
      },
      {
        key: 'pen-black',
        name: 'Ink Pen - Black',
        price: 7.29,
        min: 1,
        max: 2,
        description: 'BIC Round Stic Xtra Life Black Ballpoint Pens, Medium Point (1.0mm), 60-Count Pack',
        imageUrl: 'https://m.media-amazon.com/images/I/61Mi2KElT8L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0CHKJ4JDT',
      },
      {
        key: 'sharpie',
        name: 'Sharpie King Size Permanent Marker (12 pk)',
        price: 15.52,
        min: 1,
        max: 1,
        description: 'Extra Wide Chisel Tip, Multi-Surface Markers, Pack of 12, Permanent Black Ink',
        imageUrl: 'https://m.media-amazon.com/images/I/81lcj92-FfL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B00006IFGP',
      },
      {
        key: 'legal-pad',
        name: 'Wide Rule Legal Pad',
        price: 23.99,
        min: 1,
        max: 2,
        description: 'Legal Pad Writing Pads, Recycled Paper, 8.5"x11.75" Wide Ruled, 50 sheets, White Pack of 12',
        imageUrl: 'https://m.media-amazon.com/images/I/71gzS3ioyPL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B000087LH6',
      },
      {
        key: 'binder',
        name: '3-Ring Binder',
        price: 15.99,
        min: 1,
        max: 2,
        description: '3-Ring Binder, 1-Inch, White, 4-Pack',
        imageUrl: 'https://m.media-amazon.com/images/I/51bg5Zwyo5L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B01BRGTWOA',
      },
      {
        key: 'hanging-folders',
        name: 'Hanging File Folders',
        price: 27.7,
        min: 1,
        max: 2,
        description: 'Hanging File Folders, Letter Size, Standard Green, 1/5-Cut Tabs, 75 per box',
        imageUrl: 'https://m.media-amazon.com/images/I/91UfBxRFekL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B086QGWD2Y',
      },
      {
        key: 'file-folders',
        name: 'File Folders',
        price: 15.68,
        min: 1,
        max: 2,
        description: '1/3-Cut Tab, Assorted Positions File Folders, Letter Size, Manila - Pack of 100',
        imageUrl: 'https://m.media-amazon.com/images/I/61fuHeaBSaL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B01LYHE49W',
      },
      {
        key: 'toner-ez',
        name: 'EZ Ink Toner Cartridge (black)',
        price: 44.55,
        min: 1,
        max: 1,
        description: '4 x TN660 Black (Total 4 Pack), 2,600 Pages Per Cartridge, Brother HL-L2300D / MFC-L2700DW / DCP-L2540DW',
        imageUrl: 'https://m.media-amazon.com/images/I/81TffePc6VL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0DXV45677',
      },
      {
        key: 'toner-canon',
        name: 'True Image Toner Cartridge Replacement for Canon 057H (black)',
        price: 55.99,
        min: 1,
        max: 3,
        description: '1 pack Cartridge 057H (with chip), 10,000 pages at 5% coverage, Canon ImageCLASS MF445dw / MF455dw / LBP226dw',
        imageUrl: 'https://m.media-amazon.com/images/I/71Se3ZruoIL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B08XQKYRYJ',
      },
      {
        key: 'ink-epson',
        name: 'Remanufactured Ink Cartridge Replacement for Epson Printers',
        price: 29.99,
        min: 1,
        max: 3,
        description: 'Fooylen 802XL combo pack (1 Black, 1 Cyan, 1 Magenta, 1 Yellow), Epson Workforce Pro WF-4720 / WF-4740 / EC-4020',
        imageUrl: 'https://m.media-amazon.com/images/I/71xDP169a0L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0828BYPWV',
      },
      {
        key: 'aa-batteries',
        name: 'AA Batteries',
        price: 24.49,
        min: 1,
        max: 2,
        description: 'AA Batteries, Double A Long-Lasting Alkaline Power Batteries, 32 Count (Pack of 1)',
        imageUrl: 'https://m.media-amazon.com/images/I/81AX1sbArxL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B09RTVD1GF',
      },
      {
        key: 'aaa-batteries',
        name: 'AAA Batteries',
        price: 24.49,
        min: 1,
        max: 2,
        description: 'AAA Batteries, Triple A Long-Lasting Alkaline Power Batteries, 32 Count (Pack of 1)',
        imageUrl: 'https://m.media-amazon.com/images/I/81WjCmxPuUL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B09RTVN5GN',
      },
      {
        key: 'dry-erase',
        name: 'EXPO Low Odor Dry Erase Marker Set',
        price: 6.99,
        min: 1,
        max: 2,
        description: 'Includes Red, Blue, Green and Black markers, a 2 oz Expo white board cleaning spray, and an Expo eraser',
        imageUrl: 'https://m.media-amazon.com/images/I/8185KJTQRsL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B000MK2PZ6',
      },
      {
        key: 'desk-calendar',
        name: 'Desk Calendar (1pk)',
        price: 9.99,
        min: 1,
        max: 4,
        description: '19-month timeline, larger 1.8" x 1.5" blocks for planning and organizing',
        imageUrl: 'https://m.media-amazon.com/images/I/61arLvvhCLL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0GX5BVYLT',
      },
      {
        key: 'tape-refills',
        name: 'Transparent Tape Refills (12 pk)',
        price: 7.99,
        min: 1,
        max: 1,
        description: '12 Rolls Transparent Tape Refills, Clear Invisible, 3/4 x 1000 Inches, 1 Inch Core',
        imageUrl: 'https://m.media-amazon.com/images/I/71e4vf7uuwL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0HFNN1YGR',
      },
    ],
  },
  {
    key: 'break-room',
    title: 'Break Room',
    items: [
      {
        key: 'cups',
        name: 'Hot/Cold 12 ounce Beverage Cups',
        price: 27.99,
        min: 1,
        max: 1,
        description: 'Hot/Cold Paper Cups, White, 12-Ounce, 270 Count (Pack of 1)',
        imageUrl: 'https://m.media-amazon.com/images/I/617IVFAI5XL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B09MLSTCRY',
      },
      {
        key: 'k-cup',
        name: 'K-Cup Coffee (McCafe)',
        price: 64.99,
        min: 1,
        max: 2,
        description: 'McCafe Premium Roast K-Cup Coffee Pods (94 Count)',
        imageUrl: 'https://m.media-amazon.com/images/I/71sDWoLhhaL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B08DBYJKVW',
      },
      {
        key: 'sugar',
        name: 'Sugar',
        price: 15.62,
        min: 1,
        max: 2,
        description: '20 Ounce Sugar Canister, Pack of 6, 100% Pure Granulated Sugar, Easy Pour Lid',
        imageUrl: 'https://m.media-amazon.com/images/I/81CKsvZT2tL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0017TMTFM',
      },
      {
        key: 'creamer',
        name: 'Creamer',
        price: 15.62,
        min: 1,
        max: 2,
        description: 'Non-Dairy Coffee Creamer, 12 Ounce Canister, Pack of 6, Easy Pour Lid',
        imageUrl: 'https://m.media-amazon.com/images/I/81JpbVPaijL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B008O7LUQY',
      },
      {
        key: 'stirrers',
        name: 'Comfy Package Coffee Stirrers (1000 ct.)',
        price: 6.98,
        min: 1,
        max: 1,
        description: 'Each pack includes 1000 disposable plastic sip stir sticks, 5 inches in length',
        imageUrl: 'https://m.media-amazon.com/images/I/716q-5ID2uL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B084GYFFT9',
      },
      {
        key: 'paper-plates',
        name: 'Paper Plates',
        price: 6.92,
        min: 1,
        max: 3,
        description: '8 1/2 inch, Lunch or Light Dinner Size Printed Disposable Plate, 90 Count (Pack of 1)',
        imageUrl: 'https://m.media-amazon.com/images/I/718Tr1uB1OL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0748J34WZ',
      },
      {
        key: 'forks',
        name: 'Plastic Forks',
        price: 14.7,
        min: 1,
        max: 2,
        description: 'Heavy Weight Plastic Forks, Clear Disposable, 100 Count',
        imageUrl: 'https://m.media-amazon.com/images/I/71Hd8JPbUPL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0DDH434BH',
      },
      {
        key: 'spoons',
        name: 'Plastic Spoons',
        price: 14.7,
        min: 1,
        max: 2,
        description: 'Heavyweight Plastic Spoons, Clear Disposable, 100 Count',
        imageUrl: 'https://m.media-amazon.com/images/I/61xBEwzspaL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0DDG3LMWR',
      },
      {
        key: 'knives',
        name: 'Plastic Knives',
        price: 14.7,
        min: 1,
        max: 2,
        description: 'Heavyweight Plastic Knives, Clear Disposable, 100 Count',
        imageUrl: 'https://m.media-amazon.com/images/I/71ZN1nPbJmL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0848G9M8F',
      },
      {
        key: 'paper-towel',
        name: 'Paper Towel',
        price: 39.99,
        min: 1,
        max: 2,
        description: 'Premium Paper Towels, XL Rolls, Super Absorbent & Strong, Full Sheet 24 Rolls',
        imageUrl: 'https://m.media-amazon.com/images/I/71NSCGqzIkL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B075XP6PGK',
      },
      {
        key: 'trash-bag',
        name: '13 Gallon Trash Bag',
        price: 21.98,
        min: 1,
        max: 2,
        description: 'Tall Drawstring Trash Bags, 13 Gallon White, Unscented Leak Protection, 120 Count',
        imageUrl: 'https://m.media-amazon.com/images/I/81+Rz6Ilt-L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0FVMS3QQK',
      },
      {
        key: 'sponges',
        name: 'Heavy Duty Scrub Sponges (6 pk)',
        price: 5.97,
        min: 1,
        max: 1,
        description: 'Scotch-Brite Heavy Duty Scrub Sponges; one pack contains six sponges',
        imageUrl: 'https://m.media-amazon.com/images/I/91PkpwL474L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B004IR3044',
      },
      {
        key: 'dish-soap',
        name: 'Dish Soap (4 pk)',
        price: 16.28,
        min: 1,
        max: 1,
        description: 'Set of four 30 fl oz bottles, long-lasting bulk supply for dishwashing needs',
        imageUrl: 'https://m.media-amazon.com/images/I/71RnROGs-hL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B09B1T3ZF7',
      },
      {
        key: 'swiffer-starter',
        name: 'Swiffer WetJet Spray Mop & Cleaner Starter Kit',
        price: 28.24,
        min: 1,
        max: 1,
        description: 'Includes 1 Power Mop, 10 Pads, Cleaning Solution, Batteries',
        imageUrl: 'https://m.media-amazon.com/images/I/817arIc2UOL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B07YQDD94M',
      },
      {
        key: 'swiffer-pads',
        name: 'Swiffer WetJet Floor Cleaner Spray Mop Pad Refill (24 ct.)',
        price: 13.72,
        min: 1,
        max: 2,
        description: '24 multi-surface mopping pad refills',
        imageUrl: 'https://m.media-amazon.com/images/I/81-pQ6gjPrL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B001F0RBT2',
      },
      {
        key: 'swiffer-solution',
        name: 'Swiffer WetJet Multi-Purpose Liquid Floor Cleaner Solution Refill (2 pk)',
        price: 13.49,
        min: 1,
        max: 1,
        description: 'Cleaner Solution Refill with Gain Scent, 42.2 fl oz each (Pack of 2)',
        imageUrl: 'https://m.media-amazon.com/images/I/71tEUsX-wkL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B00BFC5IO0',
      },
    ],
  },
  {
    key: 'bath',
    title: 'Bath',
    items: [
      {
        key: 'multifold-towel',
        name: 'Multifold Towel',
        price: 32,
        min: 1,
        max: 2,
        description: 'Commercial 2-Ply White XL Multifold Paper Towels, 115 Sheets per Pack (16 Packs)',
        imageUrl: 'https://m.media-amazon.com/images/I/619vxQsQwwL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B004YK2KSM',
      },
      {
        key: 'toilet-paper',
        name: 'Toilet Paper (48 rolls)',
        price: 31.93,
        min: 1,
        max: 2,
        description: '48 Mega Rolls, each equal to 4 Regular Rolls, 320 2-ply sheets per roll',
        imageUrl: 'https://m.media-amazon.com/images/I/81M+a-AX7eL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B09R4T7L6B',
      },
      {
        key: 'hand-soap',
        name: 'Liquid Hand Soap',
        price: 15.88,
        min: 1,
        max: 2,
        description: 'Antibacterial Liquid Hand Soap, 11.25 Ounce, 6 units per case',
        imageUrl: 'https://m.media-amazon.com/images/I/815u-fMw1RL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B01LTI987W',
      },
      {
        key: 'wipes',
        name: 'Disinfecting Wipes',
        price: 10.75,
        min: 1,
        max: 2,
        description: 'Lemon & Fresh Scent, 4 canisters each with 85 count white wipes',
        imageUrl: 'https://m.media-amazon.com/images/I/71-a47bhETL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B08R17N9VV',
      },
      {
        key: 'toilet-cleaner',
        name: 'Toilet Bowl Cleaner (2 pk)',
        price: 4.98,
        min: 1,
        max: 1,
        description: 'Clinging Bleach Gel, Ocean Mist - 24 Ounces, Pack of 2',
        imageUrl: 'https://m.media-amazon.com/images/I/81Y1z35NXZL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B00W5D1MDE',
      },
      {
        key: 'air-freshener',
        name: 'Air Mist Air Freshener Spray (6 pk)',
        price: 16.44,
        min: 1,
        max: 1,
        description: 'Aerosol Can, Linen & Sky Scent, 8.8oz - 6 Count',
        imageUrl: 'https://m.media-amazon.com/images/I/71jQDqglceL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B075SM669W',
      },
      {
        key: 'tissues',
        name: 'Facial Tissues',
        price: 24.69,
        min: 1,
        max: 2,
        description: 'Ultra-Soft 3-Ply Premium Facial Tissues, 66 Tissues per Box, 18 units per case',
        imageUrl: 'https://m.media-amazon.com/images/I/6143are0p4L._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B07Y48YCJX',
      },
      {
        key: 'liners',
        name: '6-10 Gallon Office Trash Can Liners',
        price: 27.99,
        min: 1,
        max: 2,
        description: '6-10 Gallon Trash Bags (300 Count), Clear Garbage Bags',
        imageUrl: 'https://m.media-amazon.com/images/I/713jkN1fLOL._AC_SL500_.jpg',
        productUrl: 'https://www.amazon.com/dp/B0FZWZGQXS',
      },
    ],
  },
]

export const OFFICE_SUPPLY_PRIORITIES = ['Standard', 'Rush', 'Urgent'] as const

export type OfficeSupplyLineItem = {
  key: string
  name: string
  price: number
  quantity: number
  section: string
  imageUrl?: string
  productUrl?: string
}

export const OFFICE_SUPPLY_ITEM_INDEX: Record<string, OfficeSupplyItem> = Object.fromEntries(
  OFFICE_SUPPLY_SECTIONS.flatMap((section) =>
    section.items.map((item) => [item.key, item]),
  ),
)

export function formatCurrency(value: number): string {
  return value.toLocaleString('en-US', { style: 'currency', currency: 'USD' })
}
